services:
  - type: web
    name: poster-bot
    env: docker
    region: Frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        value: ebotz
      - key: OWNER_ID
        sync: false
      - key: UPSTREAM_REPO
        sync: false
      - key: UPSTREAM_BRANCH
        sync: false
      - key: PORT
        value: "80"
      - key: WEB_SERVER
        value: "true" 
